---
pre_tasks:
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600  
  
tasks:
- name: Install OpenJDK 8
  apt: "pkg={{ item }} state=latest update_cache=yes"
  with_items:
    - openjdk-8-jdk
    
- name: Set OpenJDK as stable
  command: update-java-alternatives --set {{ item }}
  with_items:
    - openjdk-8-jdk

- name: Install Tomcat 8 (TomServo)
  apt: "pkg={{ item }} state=installed"
  with_items:
    - tomcat8
    - tomcat8-admin
    
- name: Ensure Tomcat 8 is started and enabled on boot
  service: name=tomcat8 state=started enabled=yes
