---
- hosts: all
  pre_tasks:
  - name: Update apt cache
    apt:  update_cache=yes cache_valid_time=3600
    become: yes

  tasks:
  - name: Install PostgresQL and PostGIS
    apt: >
      pkg={{ item }} state=latest update_cache=no
    become: yes
    with_items:
      - postgresql
      - postgresql-contrib
      - postgis
      - pgtop

  - name: Install PgAdmin3
    apt: >
      pkg={{ item }} state=latest update_cache=no
    become: yes
    with_items:
      - pgadmin3

  - name: Register PostgresQL as a service.
    service: >
      name=postgresql
      state=started

  - name: Create .pgpass file.
    template: >
      src=pgpass.j2
      destination=/root/.pgpass
      group=postgres
      mode=0600
      owner=root
      
  - name: Get Postgres Version 
    shell: ls /etc/postgres/
    register: pg_versions

  - name: Alter /etc/postgres/<<version>>/main/postgres.config
    lineinfile: >
      dest=/etc/postgres/{{ item }}/main/postgres.config
      insertafter="^\# CONNECTIONS AND AUTHENTICATION"
      line="#listen_addresses = '*'			# what IP address(es) to listen on;"
      regexp="^\#listen_addresses = 'localhost'"
    with_items: pg_versions.stdout_lines
       


# pgpass:  hostname:port:database:username:password
