---
- hosts: all
  pre_tasks:
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=3600
    become: yes

  tasks:
  - name: Install PostgresQL and PostGIS
    apt: >
      pkg={{ item }} state=latest update_cache=no
    become: yes
    with_items:
      - postgresql
      - postgresql-contrib
      - postgis
      - pgtop

  - name: Install PgAdmin3
    apt: >
      pkg={{ item }} state=latest update_cache=no
    become: yes
    with_items:
      - pgadmin3

  - name: Register PostgresQL as a service.
    service: >
      name=postgresql
      state=started

  - name: Create .pgpass file.
    template: >
      src=pgpass.j2
      destination=/root/.pgpass
      group=postgres
      mode=0600
      owner=root

  - name: Alter /etc/postgres/<<version>>/main/postgres.config
  # To listen on on '*' instead of localhost    


# pgpass:  hostname:port:database:username:password
